In [2]:
df = pd.read_csv('Car Dataset Processed.csv')

In [3]:
df.head()

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs)
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,Comprehensive,Petrol,5,56000,First Owner,Automatic,2017,7.81,2996.0,2996.0,333.0,63.75
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,Comprehensive,Petrol,5,30615,First Owner,Automatic,2020,17.40,999.0,999.0,9863.0,8.99
2,2,2018 BMW X1 sDrive 20d xLine,Sep-18,Comprehensive,Diesel,5,24000,First Owner,Automatic,2018,20.68,1995.0,1995.0,188.0,23.75
3,3,2019 Kia Seltos GTX Plus,Dec-19,Comprehensive,Petrol,5,18378,First Owner,Manual,2019,16.50,1353.0,1353.0,13808.0,13.56
4,4,2019 Skoda Superb LK 1.8 TSI AT,Aug-19,Comprehensive,Petrol,5,44900,First Owner,Automatic,2019,14.67,1798.0,1798.0,17746.0,24.00

In [4]:
df.columns

Index(['Unnamed: 0', 'car_name', 'registration_year', 'insurance_validity',
       'fuel_type', 'seats', 'kms_driven', 'ownsership', 'transmission',
       'manufacturing_year', 'mileage(kmpl)', 'engine(cc)', 'max_power(bhp)',
       'torque(Nm)', 'price(in lakhs)'],
      dtype='object')

In [5]:
df['insurance_validity'].value_counts()

insurance_validity
Comprehensive            1081
Third Party insurance     289
Zero Dep                   64
Third Party                63
Not Available               2
Name: count, dtype: int64

In [6]:
d1={'Comprehensive':0,'Third Party insurance':1,'Zero Dep':2,'Not Available':3,'Third Party':1}
df['insurance_validity'] = df['insurance_validity'].map(d1)

In [7]:
df['insurance_validity'].value_counts()

insurance_validity
0    1081
1     352
2      64
3       2
Name: count, dtype: int64

In [8]:
df['fuel_type'].value_counts()

fuel_type
Petrol    997
Diesel    480
CNG        22
Name: count, dtype: int64

In [9]:
d2 = {'Petrol':0,'Diesel':1,'CNG':2}
df['fuel_type'] = df['fuel_type'].map(d2)

In [10]:
df['fuel_type'].value_counts()

fuel_type
0    997
1    480
2     22
Name: count, dtype: int64

In [11]:
d3={'Manual':0,'Automatic':1}
df['transmission']=df['transmission'].map(d3)
df['transmission'].value_counts()

transmission
0    832
1    667
Name: count, dtype: int64

In [12]:
d4={'First Owner':1,'Second Owner':2, 'Third Owner':3, 'Fifth Owner':5}
df['ownsership']=df['ownsership'].map(d4)
df['ownsership'].value_counts()

ownsership
1    1236
2     240
3      21
5       2
Name: count, dtype: int64

In [13]:
df['registration_year']

0       Jul-17
1       Jan-21
2       Sep-18
3       Dec-19
4       Aug-19
         ...
1494    May-22
1495    Aug-20
1496    Jun-17
1497    May-18
1498    May-18
Name: registration_year, Length: 1499, dtype: object

In [14]:
x = df[['insurance_validity','fuel_type', 'seats', 'kms_driven', 'ownsership', 'transmission']]
y = df['price(in lakhs)']
x.head()

   insurance_validity  fuel_type  seats  kms_driven  ownsership  transmission
0                   0          0      5       56000           1             1
1                   0          0      5       30615           1             1
2                   0          1      5       24000           1             1
3                   0          0      5       18378           1             0
4                   0          0      5       44900           1             1

In [15]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR

In [27]:
models = {
          'LinReg':LinearRegression(),
          'KNN-3':KNeighborsRegressor(n_neighbors = 3),
          'SVM-Poly':SVR(kernel='poly')
         }
for name,model in models.items():
    model.fit(x,y)
    sc= model.score(x,y)
    print(f"{name} score: {sc:.4f}")

LinReg score: 0.0188
KNN-3 score: 0.5928
SVM-Poly score: -0.0022

In [17]:
final_model = models['KNN-3']

In [18]:
d1={'Comprehensive':0,'Third Party insurance':1,'Zero Dep':2,'Not Available':3,'Third Party':1}
d2 = {'Petrol':0,'Diesel':1,'CNG':2}
d3={'Manual':0,'Automatic':1}
d4={'First Owner':1,'Second Owner':2, 'Third Owner':3, 'Fifth Owner':5}

In [29]:
insurance_validity = input('Insurance validity (Comprehensive/Third Party insurance/Zero Dep/Not Available): ')
fuel_type = input('Fuel Type (Petrol/Diesel/CNG): ')
seats = input('Number of Seats: ')
kms_driven = input('KMs Driven: ')
ownership = input('Ownership (First Owner/Second Owner/etc.): ')
transmission = input('Transmission Type (Manual/Automatic): ')
test_input = [[
    d1[insurance_validity],
    d2[fuel_type],
    int(seats),
    int(kms_driven),
    d4[ownership],
    d3[transmission]
]]
# Prediction
yp = final_model.predict(test_input)[0]
print(f'\nPredicted Car Price is: {yp:.2f} lakhs')

Insurance validity (Comprehensive/Third Party insurance/Zero Dep/Not Available):  Zero Dep
Fuel Type (Petrol/Diesel/CNG):  CNG
Number of Seats:  4
KMs Driven:  300000
Ownership (First Owner/Second Owner/etc.):  Second Owner
Transmission Type (Manual/Automatic):  Automatic

Predicted Car Price is: 9.38 lakhs

C:\Users\user\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(

In [33]:
import pickle
pickle.dump(final_model,open('final_model.pkl','wb'))